### ISSUE TITLE
Data base has no specifics

### ISSUE THREAD

**Issue by daniel-main** [tnadu/Everything2Everyone-Forum-WebApp#1]
Your DB diagram is all well and good but with out specifics like data types and if the fields are null and such, as well as if the database needs a specific name.  Can some more instructions be added in,  as well as maybe scripts to generate the database?

**Comment by CosminGGeorgescu** [comment]
Hello ! 
Any updates here ? I am also interested in this project.

**Comment by tnadu** [comment]
Although the amount of _attention_ our project received is greatly appreciated, it will not be maintained in any way, as it was only meant to be a one-time university project.
